src/Components/MainContainer.css, yarn.lock
=> card fixed

src/Components/MainContainer.css
#25  
- If the `Button Accessable` problem has been solved..
- please merge it..
=> [Bug] : button accessable fix

package-lock.json, package.json, src/App.js, src/Components/Container.css, src/Components/Container.js, src/Components/Menu.js, src/Components/Settings/Settings.css, src/Components/Settings/SettingsPage.js, yarn.lock
- Implemented the 'Settings' Page. Now, when you click on 'Settings' icon from the sidebar, you'll route to settings page, i.e. `/settings`
- I've used the 'React Router DOM' to route the pages, due to which made some changes in `app,js`
- Implemented multiple tabs section in Settings Page
https://github.com/SUGAM-ARORA/UniCollab/assets/132436131/0191eacc-77d8-4e00-987f-a500dba590fe
Would you mind considering assigning a level3 tag to this issue? It was quite challenging to resolve. It's entirely up to you;
I understand either way. 😉
Meanwhile, let me know if i have to make any changes in this page.
=> [FIX] Implemented Settings Page from #84

CONTRIBUTE.md
Fixes #8 
I have added the Contribute.md file 
Documentation update
- [ X ] I have performed a self-review of my code
- [ X ] I have read and followed the Contribution Guidelines.
- [ X ] I have tested the changes thoroughly before submitting this pull request.
- [ X ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X  ] I have commented my code, particularly in hard-to-understand areas.
=> created contribute.md file

src/Components/Container.css, src/Components/TopContainer.js
None
- Added transition effect to search box when clicked.
- Changed search icon and border color to blue on click, while lightening the background simultaneously.
- Rounded borders of search bar for improved appearance.
- Fixes issue #85
https://github.com/SUGAM-ARORA/UniCollab/assets/123376306/d918f097-8777-4f38-b503-93d027e3390b
before:
after:
=> Fixes issue #85: Adjust search bar visibility and appearance

src/Components/MainContainer.css, src/index.css
Fixes #104 
Updated the background surrounding the "Read More" section, along with enhancing the background of the Source Code buttons when hovered over.
https://github.com/SUGAM-ARORA/UniCollab/assets/153659573/2fc6f9a7-f02e-41fd-95c3-19a28e0a592c
=> FIXES Issue #104 (Hover Background Color Alignment Issue on 'Source Code' Button)

src/Components/Menu.css, src/Components/Menu.js, yarn.lock
**Description**
Modified the logo to function as a button that redirects users to the homepage when clicked. Also added smooth transition animation that changed opacity for better user understanding and interaction.
**Type of PR**
**Screenshots / videos**
[](https://github.com/SUGAM-ARORA/UniCollab/assets/139532908/78ee2edc-2cda-43c0-9217-02c80558d7e9)
**Checklist:**
=> Updated Logo functionality

package-lock.json, src/App.css, src/Components/MainContainer.js, src/Components/MainRightBottomCard.js, src/Components/MainRightTopCard.js, src/Components/Menu.js, src/Components/TopContainer.js, yarn.lock
Animations Added Issue No: #111 
I have added animations using vanilla CSS.
https://github.com/SUGAM-ARORA/UniCollab/assets/118285713/e772a0ef-4dbe-4877-ba11-0c48b2a6aaaa
Please review it and let me know if any changes.
=> Animations Added

src/App.js, src/Components/footer_section/BlogPage/BlogPage.css, src/Components/footer_section/BlogPage/BlogPage.js
https://github.com/SUGAM-ARORA/UniCollab/assets/132436131/408b9f39-ccd5-4989-917c-722c25c466e1
FIXES #138
=> [FIXES #138} Implemented Blog Page

.github/workflows/autocomment-iss-close.yml
Fixes #142 
The solution is to automatically post a comment on the issue whenever it gets closed. This comment should thank the issue creator for their contribution and inform them that their issue has been closed. The message can include the issue number and a friendly greeting to make it more personal. This automation ensures that every closed issue receives a consistent and timely response, improving communication and contributor experience.
=> added workflow as per issue #142

src/App.js, src/Components/footer_section/about_us/About_us.css, src/Components/footer_section/about_us/About_us.js, src/Components/footer_section/services/Services.css, src/Components/footer_section/services/Services.js
Fixes: #135 
- [x ] Feature enhancement
- [x ] I have performed a self-review of my code
- [x ] I have read and followed the Contribution Guidelines.
- [ x] I have tested the changes thoroughly before submitting this pull request.
- [ x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x ] I have commented my code, particularly in hard-to-understand areas.
Closes : #135
=> Enhanced footer: Added Services section

src/Components/CardMain.js, src/Components/MainContainer.js
Fixes: #146 
This PR improves the cleanup of the hideTimeout variable in the CardMain component. Previously, the hideTimeout variable was not being cleaned up when the component unmounted, which could potentially lead to memory leaks. This PR uses the useEffect hook to ensure that hideTimeout is cleared when the component unmounts.
This change improves the reliability and performance of the CardMain component by preventing potential memory leaks.
=> My feature branch

package-lock.json, public/index.html, src/Components/Footer.css, src/Components/Footer.js, yarn.lock
issue #150 solved
Footer logo added
=> Footer logo added

src/App.js, src/Components/footer_section/ContactUs/contact_us.css, src/Components/footer_section/ContactUs/contact_us.js
Fixes #144 
The contact page has been added to the website. It includes various details such as email, contact number, address, business hours, and a contact form where users can report technical glitches or provide suggestions for future improvements. A video demonstrating this is attached below.
https://github.com/SUGAM-ARORA/UniCollab/assets/153659573/451ad1a9-9f8f-49ec-bb25-31a2aa84a7cc
=> FIXED #144 : Added a Contact Page

src/Components/MainContainer.css, yarn.lock
The whole page was scrolling on scroll giving bad experience for feed.
I have fixed the right and left panel and made the feed scrollable so enhance the user experience of browsing feed.
#149 
=> fixed the right and left panel

package-lock.json, package.json, src/Components/Footer.css, src/Components/Footer.js, src/Components/TopContainer.js, yarn.lock
Resolved issue #178 
@SUGAM-ARORA I have updated the footer and made it responsive. please check and let me know if any changes are required
=> Updated Footer

.dockerignore, Dockerfile
Fixes #221 
I add the dockerfile and dockerignore file which helps us to make a docker image and run this app with docker locally
https://github.com/SUGAM-ARORA/UniCollab/assets/97390553/e9e90ba8-ad93-41c2-b202-ff8a247785d8
=> add dockerfile and dockerignore

form/index.html, form/script.js, form/styles.css
Hi @SUGAM-ARORA ,
I hope you're doing well. I've addressed the issue #272 and created a pull request to resolve it.
Could you please review the PR and let me know if any adjustments are needed?
Best regards,
Tanisha Garg
=> form validation

src/Components/footer_section/about_us/About_us.css
Fixes #261 
I have added a box-shadow on the about us page div section which looks more better for user interface.
=> Adding a box-shadow on the div 

deployment-app.yml, service-app.yml
Fixes #251 
i addded the kubernetes file and it work successfully
https://github.com/SUGAM-ARORA/UniCollab/assets/97390553/f9afd25c-aec0-4d49-8136-77c6aa19072e
=> add kubernetes into this

package-lock.json, package.json, src/Components/footer_section/ContactUs/contact_us.js, yarn.lock
Fixes #332 
Completed proposal provided by me , In contact page when user click on submit button than it shows success message.
https://github.com/SUGAM-ARORA/UniCollab/assets/145287513/4f622583-3cbb-48d8-813f-7a26aaa2478e
=> notification on sumbit button

src/index.css
Fixes issues closes #328 
Hey @SUGAM-ARORA 
I have added style to vertical scrollbar matching to the website.
=> Added styles to "Vertical Scroll Bar" Matching to the Website Theme

package-lock.json, package.json, src/App.js, src/Components/Login.css, src/Components/Login.js, src/Components/footer_section/ContactUs/contact_us.js, yarn.lock
Fixes #345 
Enhanced Create your Journey Page , Fixed some bugs in Project, Alignment issue also sorted
=> Create Your Journey Updated

src/Components/CardMain.js, src/Components/Footer.css, src/Components/Login.css, src/Components/MainRightBottomCard.js, src/Components/TopContainer.js
Fixes #245 
Footer Icon working has been set and it has new functionality of hover too.
=> Footer Icon working set

BACKEND/controllers/authcontrollers.js, BACKEND/routes/auth.js
Fixes #335 
change the folder structure and make it good
=> change the folder structure

src/Components/footer_section/ContactUs/contact_us.css, src/Components/footer_section/ContactUs/contact_us.js
Fixes #347
The Contact section had border-bottom , placeholder in every text item so it would have better UI .
Feature enhancement
- [X ] I have performed a self-review of my code
- [X ] I have read and followed the Contribution Guidelines.
- [X ] I have tested the changes thoroughly before submitting this pull request.
- [X ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X ] I have commented my code, particularly in hard-to-understand areas.
##Additional Description
Please close this issue with the level and label of GSSOC'24.
=> Enhancement done in the Contact page.

src/Components/MainRightBottomCard.js, src/Components/MainRightTopCard.js
Fixes #212
the view more button in the statistics and the top contributor section was not working. Now I made necessary changes for them to work
- [X ] I have performed a self-review of my code
- [ X] I have read and followed the Contribution Guidelines.
- [ X] I have tested the changes thoroughly before submitting this pull request.
- [ X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ X] I have commented my code, particularly in hard-to-understand areas.
=> made the view more button working

src/Components/menu_section/new_project/NewProject.css, src/Components/menu_section/new_project/NewProject.js
=> fixed New project page display issue

src/Components/CardMain.js, yarn.lock
added to the top button GSSOC
Fixes #287 
Added To The Top Button
So Basically we needed to add a button which takes you to the top of that Div so did that you can check
=> Added:To The Top Button

src/Components/Careers/careers.css
Fixes #374 
I have change the careers page text font, border color and add box shadow .
kindly merge my pr under GSSOC'24.
=> recreate careers page

src/Components/footer_section/ContactUs/contact_us.css, src/Components/footer_section/ContactUs/contact_us.js, yarn.lock
Fixes #403 
The "Contact Us" Page is now responsive for all devices. I've attached a video for you to look over.
https://github.com/SUGAM-ARORA/UniCollab/assets/153659573/cf49df6b-0884-49c3-956c-257db6f40734
Let me know if there are any suggestions for improvements.
Thank You!
=> Made Contact Page Responsive

src/Components/Careers/CareersPage.js, src/Components/Careers/careers.css, yarn.lock
Fixes #402 
The Careers Page is now responsive for all devices. I have made a lot of changes, so I am unable to put the videos of all the changes that I have made. So is it possible that you can check it from your end? If not, then I will upload the video for each section of change that I have made.
Let me know if there are any suggestions for improvement.
Thank You!
=> Made Careers Page Responsive

src/Components/FreeLancer/Freelancer.css, yarn.lock
Fixes #407 
This PR solves the following issues :
1.  Fixes alignment of all elements in the Freelancer Page.
2. Made the Freelancer page responsive.
As I have solved both the issues in this issue only, I request you to please upgrade the level of this issue.
Let me know if there are any suggestions for improvements.
Thank You!
=> Made Freelancer Page Responsive

src/App.js, src/Components/Login.css, src/configs/router.js
Fixes #410 
Fixes #413 
Changed the routing to v6 where all the routes are now present in `configs/router.js` where you need to just add the path and element like 
```
{
path: '/route/:id',
element: <ElementNeeded/>
},
```
Screenshots :
#413
Footer not overlapping now
Updated the react router dom to version 6 with createBrowserRouter .
and fixed the footer placement
=> Update the react-router-dom and Fix Footer , 2 issues completed

src/Components/Login.css, src/Components/Login.js, src/Components/footer_section/BlogPage/BlogPage.css
Fixes #437 
@SUGAM-ARORA I have made the UI Refinements: Adding Shadows and Aligning Login Page Elements in the page. Kindly review this.
=> UI Refinements: Adding Shadows and Aligning Login Page Elements

package-lock.json, package.json, src/App.js, yarn.lock
Fixes #358 
I have added the appropriate tags to make the website SEO friendly
Kindly let me know if there are any changes to be made.
=> SEO tags added

src/Components/footer_section/FAQPage/FAQPage.css, src/Components/footer_section/FAQPage/FAQPage.js
Fixes #449 
@SUGAM-ARORA I have made the FAQ Page styling like the Blog Page. Kindly review this.
=> Discover Answers: A Blog-Style FAQ

src/Components/Footer.js, yarn.lock
Hello Project Admin
I Added Icons to Navbar - 
Fixes #441 
Kindly Please go through this PR @SUGAM-ARORA
=> Added Icons to Footer

src/Components/RateUs.css, src/Components/RateUs.js, src/Components/TopContainer.js, src/configs/router.js
Hello Project Admin
I Added Rate Us Page - Solved #442 
Kindly Please go through this PR @SUGAM-ARORA 
https://github.com/SUGAM-ARORA/UniCollab/assets/161804629/b25a385e-3969-4cd6-9398-38b3399b7007
=> Added Rate us Option

src/Components/Firebase/Firebase.js, src/Components/Login.css, src/Components/Login.js
Fixes #483 
@SUGAM-ARORA I have setup Github login using firebase. Kindly review this PR and make sure to allow Github authentication on firebase portal
=> Github Login

public/index.html
Hey @SUGAM-ARORA 
Fixes #519 
I have hidden the cursor trail effect in the mobile view 
https://github.com/user-attachments/assets/c35d7ba4-43ce-4c7f-9e14-dfa05f551777
=> Hide The Cursor Trail Effect in Mobile View

src/App.js, src/Components/feedback/feedback.css, src/Components/feedback/feedbackform.js, src/configs/router.js, yarn.lock
Fixes #515 
The Feedback form has been added to the website.
- A 'Help Us Improve!' button has been added to the project's main page.
- The Feedback page is also made responsive.
https://github.com/user-attachments/assets/9e931490-e91f-4a34-967f-935138d51821
=> Added Feedback Form

src/Components/Firebase/Firebase.js, src/Components/Login.js
Fixes #518 
@SUGAM-ARORA I have added the Phone number Authentication . Kindly make sure to allow the phone number authentication in the firebase. Kindly review this.
=> Adding Phone Number Authentication

src/Components/footer_section/Mail/Mail.css, yarn.lock
Fixes #533 
The footer is now responsive to all the devices. There are some problems at smaller widths, which are because the navbar is not responsive for all devices, and for that, an issue #542 has been opened.
https://github.com/user-attachments/assets/d890f9de-2177-4531-bb52-76dce000e4b1
I will also attach the video to show what the footer will look like after removing the navigation bar.
https://github.com/user-attachments/assets/80fd3951-0492-4378-8557-d1b347009b68
=> Made Footer Responsive

src/Components/feedback/feedback.css
Fixes #544 
@SUGAM-ARORA I have done the Enhancement of  the Design of The 'Help Us Improve' Page. Kindly review this.
=> Enhancing the Design of The 'Help Us Improve' Page

src/Components/gototop.js
=> Fix Overlapping of Feedback button and Scroll to top buttons 

src/Components/Firebase/Firebase.js, src/Components/Login.js
Fixes #552 
@SUGAM-ARORA I have added Twitter Authentication to the website. Make sure to allow Twitter Authentication in the Firebase. Kindly review this.
=> Adding Twitter Authentication

LEARN.md
Fixes #536 
change the learn.md for kubernetes and docker
=> change learn.md

package-lock.json, src/Components/Login.css, yarn.lock
Fixes #573 , Fixes #572 
Both login and signup pages have been fixed under this single PR only.
=> Fixed Login and Signup Pages

src/Components/Login.css, src/Components/Login.js, src/Components/Menu.css, src/Components/Menu.js, src/Components/TopContainer.css, src/Components/menu_section/my_projects/MyProjects.css
Fixes #617 
@SUGAM-ARORA I have added the expandable sidebar to the main page. Kindly review this.
=> Expandable Sidebar with Toggle Button

src/Components/Menu.css, src/Components/Menu.js, src/Components/Popular.js, src/Components/TopContainer.css
Fixes #621 
@SUGAM-ARORA I have made the sidebar page to not overlap with the navbar, Add hover in the sidebar and also made the setting of the Popular Page similar to that of Feed Page. Kindly review this.
=> Sidebar Page Overlapping

src/Components/MainContainer.css, src/Components/MainContainer.js, src/Components/TopContainer.css
Fixes #623
@SUGAM-ARORA I have added the buttons for the sort by Page. Kindly review this.
=> Making of Sort By Buttons

src/Components/Footer.js
issue no :- #599 
added x to twitter logo
=> added x to twitter logo

BACKEND/package-lock.json, BACKEND/server.js, package-lock.json, package.json, src/Components/Settings/SettingsPage.js
Fixes #630 
@SUGAM-ARORA I have connected the Backend in the settings Page. Kindly review this.
=> Settings Page Config

package-lock.json, src/Components/Contributors.css, src/Components/Contributors.js, src/Components/Footer.js, src/configs/router.js
Hey @SUGAM-ARORA 
- issue closes #637 
I have added a dedicated contributors page for Unicollab
=> Created Our Contributors Page for Unicollab

src/Components/Container.css, src/Components/TopContainer.css, src/Components/TopContainer.js
=> Fixed the navbar for mobile sccreen

BACKEND/package-lock.json, BACKEND/package.json, BACKEND/server.js, package-lock.json, package.json, src/Components/Stopwatch.js
Fixes #650 
@SUGAM-ARORA I have added the code for the connection of saving the recording. U jsut need to add your own mongodb account details for this to work. Kindly review this.
=> Recording Saving

src/Components/Delicious/Delicious.css, src/Components/Delicious/Delicious.js, src/Components/Menu.js, src/configs/router.js
Fixes #640 
@SUGAM-ARORA I have added the Delicious Page to the website. Kindly review this.
=> Implementing Delicious Page

src/Components/Menu.js, src/Components/footer_section/Pricing/pricing.css, src/Components/wallet/Wallet.css, src/Components/wallet/Wallet.js, src/configs/router.js
Fixes #608 
The Wallet Page has been implemented. Let me know if there are any suggestions for improvements.
https://github.com/user-attachments/assets/e617a1f5-483f-412b-8903-603163645346
=> Added Wallet Page

src/Components/Menu.js, src/Components/Trending/Trending.css, src/Components/Trending/Trending.js, src/configs/router.js
Fixes #641 
@SUGAM-ARORA I have added the Trending Page to the website. Kindly review this.
=> Trending Now Page

BACKEND/server.js, src/Components/Contributors.css, src/Components/Contributors.js, src/Components/RateUs.js
Fixes #661 
@SUGAM-ARORA I have set up the Backend of the Rate Us Page.Kindly review this.
=> Rate Us Backend

src/Components/TopContainer.css, src/Components/TopContainer.js
Fixes #667 
@SUGAM-ARORA I have set the search icon to be back in the Search Bar. Kindly review this.
=>  Search Icon Position

src/App.js, src/Components/Login.js, src/Components/forgot.css, src/Components/forgot.js, src/configs/router.js
Fixes #670 
@SUGAM-ARORA I have added the Reset Password Page to the Login Page. Kindly review this.
=> Reset Password Page

BACKEND/Express.js, src/Components/MainRightBottomCard.js, src/Components/Settings/Settings.css, src/Components/forgot.js
Fixes #672 
@SUGAM-ARORA I have added the Backend to the Forgot Page as well as enhanced the styling in Settings Page. Kindly review this.
=> Forgot Backend

src/App.css, src/App.js, src/Components/CardMain.css, src/Components/CardMain.js, src/Components/ChatbotIcon.css, src/Components/Footer.js, src/Components/MainContainer.js, src/Components/Menu.js, src/Components/TopContainer.css
Fixes #684 
Fixes #686 
Made changes to few files and fixed components alignment for mobiles.
I mistakenly committed my 2nd issue changes (#686) into this branch. Please take into consideration that this Pull Request is for solving two issues. 
So Please try to give this PR level3.
**1st issue -** 
**2nd issue -**
=> Made needed changes and fixed components alignment

src/Components/TopContainer.css, src/Components/TopContainer.js, src/Components/searchResults.js
Fixes #346 
@SUGAM-ARORA I have added the features in the search results for different menu projects. Kindly review this.
=> Improve features on search results

src/Components/menu_section/my_projects/MyProjects.css, src/Components/menu_section/my_projects/MyProjects.js, src/Components/menu_section/new_project/NewProject.css
Fixes #698 
Made few changes to several files and Improved look and feel of Projects page and also projects are correctly integrated in the page. I have worked hard and made the page responsive for mobiles.
=> Updated Projects Page

src/Components/TopContainer.css, src/Components/TopContainer.js
Fixes #721 
@SUGAM-ARORA I have added toggle colour for the navbar icons also. Kindly review this.
=> Different Colours Icons Naving

src/Components/TopContainer.css, src/Components/TopContainer.js
Fixes #723 
Navbar for mobile screen
=> Fixed navbar for mobile screen

src/Components/footer_section/BlogPage/BlogPage.css, src/Components/footer_section/BlogPage/BlogPage.js
Fixes #593 
the current blog page desing is very unattractive,  Date is running in center, the arrows are not vertically aligned, text is not left aligned etc.
In this pr i have fixed the design of the blog page via added radius to the border and properly aligning the things. Along with that there is some code formatting.
=> improved the blog page design

src/Components/feedback/feedback.css, src/Components/feedback/feedbackform.js, src/Components/footer_section/Pricing/pricing.css
Fixes #769
Proper Alignment of the home icon in pricing and help us improve page, and light mode improved in help us improve page
Nothing, just can refer to ss attached!
=> Fix: Alignment of home icon

src/Components/MainContainer.css, src/Components/TopContainer.css, src/Components/TopContainer.js
=> navbar buttons alignment

BACKEND/server.js
Added error handling
Added comprehensive error handling for all major routes, including file uploads, database connections, profile and account endpoints, and feedback submission. This ensures that the API responds appropriately to missing or invalid data, and logs errors for further investigation.
Profile and Account Endpoints: Added validation for required fields and error handling for data updates and retrieval.
Database Connection: Application exits gracefully if unable to connect to MongoDB.
File Uploads: Ensured that all fields and attachments are properly validated.
Feedback Submission: Ensured both emoji and feedback are required.
This update enhances the robustness of the application by adding detailed error handling, improving user experience, and ensuring the server is …
=> Update server.js with better error handling

src/Components/FreeLancer/Freelancer.css
Fixes #809 
This pull request addresses the issue of improving the footer's design and the freelancer card component positioning per Issue #809 .
Changes Made:
Updated Freelancer.css to enhance visual appeal.
Ensured the footer is placed at bottom and not overlapping the card component
Tested the changes in the file to maintain layout and functionality.
- [x ] I have performed a self-review of my code
- [x ] I have read and followed the Contribution Guidelines.
- [x ] I have tested the changes thoroughly before submitting this pull request.
- [x ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
=> Fixed the footer and freelancer card

src/Components/footer_section/ContactUs/contact_us.css, src/Components/footer_section/ContactUs/contact_us.js
Fixes [#820]( https://github.com/SUGAM-ARORA/UniCollab/issues/820)
Fixed the unaligned elements of the page
OLD:
NEW:
=> chore: Update ContactUs component CSS

src/Components/Readmore.css, src/Components/Readmore.js
Fixes [#820](https://github.com/SUGAM-ARORA/UniCollab/issues/822)
OLD:
NEW:
=> feature: Improved UI of read more page
